version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 6
  versioning-strategy: "increase"
  ignore:
    # ignore all GitHub linguist patch updates
    - dependency-name: "node-fetch"
      update-types: ["version-update:semver-major"]
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: monthly
