version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "11:00"
  open-pull-requests-limit: 3
  ignore:
    # ignore all GitHub linguist patch updates
    - dependency-name: "node-fetch"
      update-types: ["version-update:semver-major"]